// Generated by CoffeeScript 1.8.0
var DetailEditor, detailEditor;

DetailEditor = (function() {
  function DetailEditor() {}

  DetailEditor.prototype.addImageLoadEvent = function(canvas) {
    var handleImage, imageLoader;
    handleImage = function(e) {
      var reader;
      reader = new FileReader();
      reader.onload = function(event) {
        var img;
        img = new Image();
        img.src = event.target.result;
        return img.onload = function() {
          var image;
          image = new fabric.Image(img);
          image.set({
            angle: 0,
            padding: 10,
            cornersize: 10
          });
          if (image.width > 100) {
            image.width = 100;
          }
          if (image.height > 100) {
            image.height = 100;
          }
          if (image.type === void 0) {
            image.type = "image";
          }
          if (canvas.lastObject !== void 0) {
            canvas.remove(canvas.lastObject);
          }
          image.setCoords(0, 0);
          canvas.add(image);
          canvas.centerObject(image);
          canvas.renderAll();
          return canvas.lastObject = image;
        };
      };
      return reader.readAsDataURL(e.target.files[0]);
    };
    imageLoader = document.getElementById("uploadImgBtn");
    return imageLoader.addEventListener("change", handleImage, false);
  };

  DetailEditor.prototype.init = function() {
    var ctx;
    this.canvas = new fabric.Canvas('detailLoad', {
      selection: false
    });
    this.addImageLoadEvent(this.canvas);
    return ctx = this.canvas.getContext("2d");
  };

  return DetailEditor;

})();

detailEditor = new DetailEditor();
